services:
  db:
    container_name: albion_db
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env
    
volumes:
  postgres-data: