services:
  banco_de_dados:
    container_name: albion_db
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env

  flyway:
    image: flyway/flyway:latest
    container_name: flyway_migrator
    depends_on:
      - banco_de_dados
    environment:
      FLYWAY_CLEAN_DISABLED: "false"
      FLYWAY_URL: jdbc:postgresql://banco_de_dados:5432/albion
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: postgres
    volumes:
      - ./migrations:/flyway/sql
    entrypoint: [ "flyway", "migrate" ]

volumes:
  postgres-data:
    driver: local
