site_name: Albion 

repo_name: Banco de Dados Albion
repo_url: https://github.com/daviRolvr/2025.1-Albion

nav: 
  - Início: index.md
  - Entrega 1:
    - MER: section1/Entrega-1/1-MER.md
    - Modelo Relacional: sections/Entrega-1/2-ModeloRelacional.md
    - Dicionário de Dados: sections/Entrega-1/3-DicionarioDados.md
    - Vídeo de Apresentação: sections/Entrega-1/4-VideoApresentacao.md

heme: 
  name: material
  language: pt-BR
  favicon: assets/logoAlbion.png
  logo: assets/logoAlbion.png

  features:
    - content.code.annotate
      - content.tabs.link
      - header.autohide
      - navigation.instant
      - navigation.top
      - navigation.tracking
  
  palette:
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: red
    accent: red
    toggle:
      icon: material/weather-night
      name: Tema claro

  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: red
    accent: red
    toggle:
      icon: material/weather-sunny
      name: Tema escuro