CREATE TABLE IF NOT EXISTS INVENTARIO (
    id_personagem INTEGER PRIMARY KEY REFERENCES public.PERSONAGEM (id_personagem),
    slots INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS INVENTARIO_EQUIPADOS (
    id_personagem INTEGER PRIMARY KEY REFERENCES public.PERSONAGEM (id_personagem),
    slot_arma VARCHAR(100),
    slot_armadura VARCHAR(100),
    slot_artefato VARCHAR(100)
)